create table provinces
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table provinces
    owner to postgres;

create table cities
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255) not null,
    province_id bigint       not null
        constraint fkcf2ndxcsekl26rrkb9egbhq20
            references provinces
);

alter table cities
    owner to postgres;

create table roles
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table roles
    owner to postgres;

create table sports
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table sports
    owner to postgres;

create table teams
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(255) not null,
    sport_id bigint       not null
        constraint fkc2kpkonbxgprdwilacrp2tkp8
            references sports
);

alter table teams
    owner to postgres;

create table ticket_categories
(
    id        bigint generated by default as identity
        primary key,
    amenities jsonb,
    name      varchar(255) not null
);

alter table ticket_categories
    owner to postgres;

create table tournaments
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table tournaments
    owner to postgres;

create table users
(
    id            bigint generated by default as identity
        primary key,
    email         varchar(255) not null,
    first_name    varchar(255) not null,
    is_active     boolean      not null,
    last_name     varchar(255) not null,
    password_hash varchar(255) not null,
    phone         varchar(255) not null,
    city_id       bigint       not null
        constraint fkn36jwt4acj3il2ixvv2c0ncco
            references cities,
    role_id       bigint       not null
        constraint fkp56c1712k691lhsyewcssf40f
            references roles
);

alter table users
    owner to postgres;

create table logs
(
    id          bigint generated by default as identity
        primary key,
    action      varchar(255) not null,
    action_date timestamp(6) not null,
    user_id     bigint       not null
        constraint fkgqy8beil5y4almtq1tiyofije
            references users
);

alter table logs
    owner to postgres;

create table reservations
(
    id          bigint generated by default as identity
        primary key,
    expired_at  timestamp(6),
    reserved_at timestamp(6) not null,
    status      varchar(255) not null
        constraint reservations_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])),
    user_id     bigint       not null
        constraint fkb5g9io5h54iwl2inkno50ppln
            references users
);

alter table reservations
    owner to postgres;

create table venues
(
    id       bigint generated by default as identity
        primary key,
    address  varchar(255) not null,
    capacity integer      not null,
    name     varchar(255) not null,
    city_id  bigint       not null
        constraint fkm3mi79lpgax9ln1v2kbrc9fsb
            references cities
);

alter table venues
    owner to postgres;

create table matches
(
    id            bigint generated by default as identity
        primary key,
    datetime      timestamp(6) not null,
    status        varchar(255) not null
        constraint matches_status_check
            check ((status)::text = ANY
                   ((ARRAY ['SCHEDULED'::character varying, 'ON_SALE'::character varying, 'SOLD_OUT'::character varying, 'IN_PROGRESS'::character varying, 'FINISHED'::character varying, 'CANCELLED'::character varying, 'POSTPONED'::character varying])::text[])),
    guest_team_id bigint       not null
        constraint fkn9oyy00pityvaekt35sia05cv
            references teams,
    host_team_id  bigint       not null
        constraint fk7b3141h0f8f6qtqhsqqlh6rjy
            references teams,
    sport_id      bigint       not null
        constraint fklo85d6syiegp2utk9l2vewxq5
            references sports,
    tournament_id bigint       not null
        constraint fkeeniokyjgo5k6rmhjujatn27i
            references tournaments,
    venue_id      bigint       not null
        constraint fkgfd82fqocrak8cp07iegd68fn
            references venues
);

alter table matches
    owner to postgres;

create table seats
(
    id                 bigint generated by default as identity
        primary key,
    position_number    integer      not null,
    position_row_label varchar(255) not null,
    position_section   varchar(255) not null,
    venue_id           bigint       not null
        constraint fkfahhtb0bb0u1wcnqqys0iehmo
            references venues
);

alter table seats
    owner to postgres;

create table match_seats
(
    id                 bigint generated by default as identity
        primary key,
    price              numeric(38, 2) not null,
    status             varchar(255)   not null
        constraint match_seats_status_check
            check ((status)::text = ANY
                   ((ARRAY ['AVAILABLE'::character varying, 'RESERVED'::character varying, 'SOLD'::character varying, 'BLOCKED'::character varying])::text[])),
    match_id           bigint         not null
        constraint fkll740wd2td5wp4bth0jwtk12l
            references matches,
    seat_id            bigint         not null
        constraint fknf0ykdil4auidynaq25bvopc5
            references seats,
    ticket_category_id bigint         not null
        constraint fktfxdjbi6cwbtubs6y55wayor
            references ticket_categories
);

alter table match_seats
    owner to postgres;

create table reservation_items
(
    id             bigint generated by default as identity
        primary key,
    price_at_time  numeric(19, 2) not null,
    match_seat_id  bigint         not null
        constraint fkth8dqkmcf8o7fg70nl8v0ktv9
            references match_seats,
    reservation_id bigint         not null
        constraint fkahatpyi4mk3o5dcqt7d51r31k
            references reservations
);

alter table reservation_items
    owner to postgres;

create table tickets
(
    id                  bigint generated by default as identity
        primary key,
    issued_at           timestamp(6) not null,
    qr_payload          text,
    status              varchar(255) not null
        constraint tickets_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ISSUED'::character varying, 'USED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])),
    ticket_code         varchar(50)  not null
        constraint ukcvl4jbu5fln08ltem9rrmtp8w
            unique,
    used_at             timestamp(6),
    reservation_item_id bigint       not null
        constraint ukaehd9blwn3c189uxeuya80p5k
            unique
        constraint fk7e6s7gu134q0jfek19r78pwpm
            references reservation_items
);

alter table tickets
    owner to postgres;

create table cancellations
(
    id           bigint generated by default as identity
        primary key,
    processed_at timestamp(6),
    reason       text         not null,
    requested_at timestamp(6) not null,
    status       varchar(255) not null
        constraint cancellations_status_check
            check ((status)::text = ANY
                   ((ARRAY ['REQUESTED'::character varying, 'PROCESSING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'DONE'::character varying])::text[])),
    ticket_id    bigint       not null
        constraint uk7d7qa629j5mgg2elgtdc2wryl
            unique
        constraint fk3itgpj32neni75dwjmdu5klrf
            references tickets,
    user_id      bigint       not null
        constraint fk33w7524mgghj8pnfu2om1aave
            references users
);

alter table cancellations
    owner to postgres;

create table wallets
(
    id      bigint generated by default as identity
        primary key,
    credit  numeric(19, 2) not null,
    user_id bigint         not null
        constraint uksswfdl9fq40xlkove1y5kc7kv
            unique
        constraint fkc1foyisidw7wqqrkamafuwn4e
            references users
);

alter table wallets
    owner to postgres;

create table payment_methods
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255) not null,
    status      varchar(255) not null
        constraint payment_methods_status_check
            check ((status)::text = ANY
                   ((ARRAY ['SUCCESSFUL'::character varying, 'FAILED'::character varying, 'PENDING'::character varying])::text[]))
);

alter table payment_methods
    owner to postgres;

create table payments
(
    id                bigint generated by default as identity
        primary key,
    amount            numeric(19, 2) not null,
    payment_date      timestamp(6)   not null,
    status            varchar(255)   not null
        constraint payments_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])),
    transaction_ref   varchar(255)
        constraint ukjwk4x78utnlycetjq9ulvm7tr
            unique,
    payment_method_id bigint         not null
        constraint fkce1n8pa67lq4l57l9mhugdgab
            references payment_methods,
    reservation_id    bigint         not null
        constraint fkp8yh4sjt3u0g6aru1oxfh3o14
            references reservations
);

alter table payments
    owner to postgres;

create table issue_reports
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    description text         not null,
    resolved_at timestamp(6),
    status      varchar(255) not null
        constraint issue_reports_status_check
            check ((status)::text = ANY
                   ((ARRAY ['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])),
    subject     varchar(255) not null,
    updated_at  timestamp(6),
    payment_id  bigint
        constraint fk4u2nabh6tcct29r73p0b6bvey
            references payments,
    user_id     bigint
        constraint fkh1b3ubh9t7f8quo02v7rx91s7
            references users
);

alter table issue_reports
    owner to postgres;

