services:
  postgres:
    image: postgres:18
    container_name: gangofthree-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aminamin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - gangofthree-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gangofthree-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gangofthree-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: aminamin
      
      SPRING_DATA_REDIS_HOST: redis-gangofthree
      SPRING_DATA_REDIS_PORT: 6379
      
      SPRING_ELASTICSEARCH_URIS: http://gangofthree-elasticsearch:9200
      
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gangofthree-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gangofthree-frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://gangofthree-backend:8081
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - gangofthree-network

volumes:
  postgres_data:

networks:
  gangofthree-network:
    external: true
