-- ================================================================== Creating Tables ======================================================================== 

create table payment_methods
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255) not null,
    status      varchar(255) not null
        constraint payment_methods_status_check
            check ((status)::text = ANY
                   ((ARRAY ['SUCCESSFUL'::character varying, 'FAILED'::character varying, 'PENDING'::character varying])::text[]))
);

alter table payment_methods
    owner to postgres;

create table provinces
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table provinces
    owner to postgres;

create table cities
(
    id          bigint generated by default as identity
        primary key,
    province_id bigint       not null
        constraint fkcf2ndxcsekl26rrkb9egbhq20
            references provinces,
    name        varchar(255) not null
);

alter table cities
    owner to postgres;

create table sports
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table sports
    owner to postgres;

create table teams
(
    id       bigint generated by default as identity
        primary key,
    sport_id bigint       not null
        constraint fkc2kpkonbxgprdwilacrp2tkp8
            references sports,
    name     varchar(255) not null
);

alter table teams
    owner to postgres;

create table ticket_categories
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255) not null,
    amenities jsonb
);

alter table ticket_categories
    owner to postgres;

create table tournaments
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table tournaments
    owner to postgres;

create table users
(
    is_active     boolean      not null,
    city_id       bigint       not null
        constraint fkn36jwt4acj3il2ixvv2c0ncco
            references cities,
    id            bigint generated by default as identity
        primary key,
    email         varchar(255) not null,
    first_name    varchar(255) not null,
    last_name     varchar(255) not null,
    password_hash varchar(255) not null,
    phone         varchar(255) not null
        constraint chk_user_phone
            check ((phone)::text ~ '^(09|9)[0-9]{9}$'::text),
    role          varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['BUYER'::character varying, 'SUPPORT'::character varying])::text[]))
);

alter table users
    owner to postgres;

create table logs
(
    action_date timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    user_id     bigint       not null
        constraint fkgqy8beil5y4almtq1tiyofije
            references users,
    action      varchar(255) not null
);

alter table logs
    owner to postgres;

create table reservations
(
    expired_at  timestamp(6),
    id          bigint generated by default as identity
        primary key,
    reserved_at timestamp(6) not null,
    user_id     bigint       not null
        constraint fkb5g9io5h54iwl2inkno50ppln
            references users,
    status      varchar(255) not null
        constraint reservations_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])),
    constraint chk_reservation_dates
        check ((expired_at IS NULL) OR (reserved_at <= expired_at))
);

alter table reservations
    owner to postgres;

create table cancellations
(
    id             bigint generated by default as identity
        primary key,
    processed_at   timestamp(6),
    requested_at   timestamp(6) not null,
    reservation_id bigint       not null
        unique
        constraint fkagn8cqvm03koa4w6pdn1pxvcn
            references reservations,
    user_id        bigint       not null
        constraint fk33w7524mgghj8pnfu2om1aave
            references users,
    reason         text         not null,
    status         varchar(255) not null
        constraint cancellations_status_check
            check ((status)::text = ANY
                   ((ARRAY ['REQUESTED'::character varying, 'PROCESSING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'DONE'::character varying])::text[])),
    constraint chk_cancellation_dates
        check ((processed_at IS NULL) OR (requested_at <= processed_at))
);

alter table cancellations
    owner to postgres;

create table payments
(
    amount            numeric(19, 2) not null,
    id                bigint generated by default as identity
        primary key,
    payment_date      timestamp(6)   not null,
    payment_method_id bigint         not null
        constraint fkce1n8pa67lq4l57l9mhugdgab
            references payment_methods,
    reservation_id    bigint         not null
        constraint fkp8yh4sjt3u0g6aru1oxfh3o14
            references reservations,
    status            varchar(255)   not null
        constraint payments_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])),
    transaction_ref   varchar(255)
        unique
);

alter table payments
    owner to postgres;

create table issue_reports
(
    created_at  timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    payment_id  bigint
        constraint fk4u2nabh6tcct29r73p0b6bvey
            references payments,
    resolved_at timestamp(6),
    updated_at  timestamp(6),
    user_id     bigint
        constraint fkh1b3ubh9t7f8quo02v7rx91s7
            references users,
    description text         not null,
    status      varchar(255) not null
        constraint issue_reports_status_check
            check ((status)::text = ANY
                   ((ARRAY ['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])),
    subject     varchar(255) not null,
    constraint chk_issue_dates
        check (((resolved_at IS NULL) OR (created_at <= resolved_at)) AND
               ((updated_at IS NULL) OR (created_at <= updated_at)))
);

alter table issue_reports
    owner to postgres;

create table venues
(
    capacity integer      not null
        constraint chk_venue_capacity
            check (capacity > 0),
    city_id  bigint       not null
        constraint fkm3mi79lpgax9ln1v2kbrc9fsb
            references cities,
    id       bigint generated by default as identity
        primary key,
    address  varchar(255) not null,
    name     varchar(255) not null
);

alter table venues
    owner to postgres;

create table matches
(
    datetime      timestamp(6) not null,
    guest_team_id bigint       not null
        constraint fkn9oyy00pityvaekt35sia05cv
            references teams,
    host_team_id  bigint       not null
        constraint fk7b3141h0f8f6qtqhsqqlh6rjy
            references teams,
    id            bigint generated by default as identity
        primary key,
    sport_id      bigint       not null
        constraint fklo85d6syiegp2utk9l2vewxq5
            references sports,
    tournament_id bigint       not null
        constraint fkeeniokyjgo5k6rmhjujatn27i
            references tournaments,
    venue_id      bigint       not null
        constraint fkgfd82fqocrak8cp07iegd68fn
            references venues,
    status        varchar(255) not null
        constraint matches_status_check
            check ((status)::text = ANY
                   ((ARRAY ['SCHEDULED'::character varying, 'ON_SALE'::character varying, 'SOLD_OUT'::character varying, 'IN_PROGRESS'::character varying, 'FINISHED'::character varying, 'CANCELLED'::character varying, 'POSTPONED'::character varying])::text[]))
);

alter table matches
    owner to postgres;

create table seats
(
    position_number    integer      not null
        constraint chk_seat_number
            check (position_number > 0),
    id                 bigint generated by default as identity
        primary key,
    venue_id           bigint       not null
        constraint fkfahhtb0bb0u1wcnqqys0iehmo
            references venues,
    position_row_label varchar(255) not null,
    position_section   varchar(255) not null
);

alter table seats
    owner to postgres;

create table match_seats
(
    price              numeric(38, 2) not null
        constraint chk_seat_price
            check (price >= (0)::numeric),
    id                 bigint generated by default as identity
        primary key,
    match_id           bigint         not null
        constraint fkll740wd2td5wp4bth0jwtk12l
            references matches,
    seat_id            bigint         not null
        constraint fknf0ykdil4auidynaq25bvopc5
            references seats,
    ticket_category_id bigint         not null
        constraint fktfxdjbi6cwbtubs6y55wayor
            references ticket_categories,
    status             varchar(255)   not null
        constraint match_seats_status_check
            check ((status)::text = ANY
                   ((ARRAY ['AVAILABLE'::character varying, 'RESERVED'::character varying, 'SOLD'::character varying, 'BLOCKED'::character varying])::text[]))
);

alter table match_seats
    owner to postgres;

create table reservation_items
(
    price_at_time  numeric(19, 2) not null
        constraint chk_price_at_time
            check (price_at_time >= (0)::numeric),
    id             bigint generated by default as identity
        primary key,
    match_seat_id  bigint         not null
        constraint fkth8dqkmcf8o7fg70nl8v0ktv9
            references match_seats,
    reservation_id bigint         not null
        constraint fkahatpyi4mk3o5dcqt7d51r31k
            references reservations
);

alter table reservation_items
    owner to postgres;

create table tickets
(
    id                  bigint generated by default as identity
        primary key,
    issued_at           timestamp(6) not null,
    reservation_item_id bigint       not null
        unique
        constraint fk7e6s7gu134q0jfek19r78pwpm
            references reservation_items,
    used_at             timestamp(6),
    ticket_code         varchar(50)  not null
        unique,
    qr_payload          text,
    status              varchar(255) not null
        constraint tickets_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ISSUED'::character varying, 'USED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])),
    constraint chk_ticket_dates
        check ((used_at IS NULL) OR (issued_at <= used_at))
);

alter table tickets
    owner to postgres;

create table wallets
(
    credit  numeric(19, 2) not null
        constraint chk_wallet_credit
            check (credit >= (0)::numeric),
    id      bigint generated by default as identity
        primary key,
    user_id bigint         not null
        unique
        constraint fkc1foyisidw7wqqrkamafuwn4e
            references users
);

alter table wallets
    owner to postgres;


-- ==================================================================== Inserting Data Queries ===============================================================


INSERT INTO provinces (name) VALUES ('تهران'), ('اصفهان'), ('فارس'), ('خراسان رضوی'), ('آذربایجان شرقی'), ('خوزستان'), ('مازندران'), ('گیلان'), ('کرمان'), ('البرز');


INSERT INTO sports (name) VALUES ('فوتبال'), ('والیبال'), ('بسکتبال'), ('کشتی'), ('تکواندو'), ('تنیس'), ('فوتسال'), ('هندبال'), ('شنا'), ('دو و میدانی');


INSERT INTO ticket_categories (name, amenities) VALUES
('VIP', '{"parking": true, "food": true}'),
('VVIP', '{"parking": true, "food": true, "lounge": true}'),
('Regular', '{"parking": false, "food": false}'),
('Premium', '{"parking": true, "food": false}'),
('Economy', '{}'),
('Student', '{}'),
('Family', '{"kid_zone": true}'),
('Disabled', '{"wheelchair_access": true}'),
('Early Bird', '{}'),
('Last Minute', '{}');


INSERT INTO payment_methods (description, status) VALUES
('درگاه ملت', 'ALLOWED'),
('درگاه سامان', 'ALLOWED'),
('درگاه ملی', 'ALLOWED'),
('کارت به کارت', 'ALLOWED'),
('کیف پول', 'ALLOWED'),
('پرداخت در محل', 'SUSPENDED'),
('درگاه پاسارگاد', 'ALLOWED'),
('درگاه پارسیان', 'ALLOWED'),
('آپ', 'ALLOWED'),
('زرین پال', 'ALLOWED');

INSERT INTO tournaments (name) VALUES ('لیگ برتر'), ('جام حذفی'), ('جام جهانی'), ('لیگ قهرمانان'), ('المپیک'), ('جام ملت‌ها'), ('لیگ دسته یک'), ('مسابقات دوستانه'), ('لیگ جهانی'), ('تورنمنت چهارجانبه');


INSERT INTO cities (name, province_id) VALUES ('تهران', 1), ('اصفهان', 2), ('شیراز', 3), ('مشهد', 4), ('تبریز', 5), ('اهواز', 6), ('ساری', 7), ('رشت', 8), ('کرمان', 9), ('کرج', 10);


INSERT INTO teams (name, sport_id) VALUES ('استقلال', 1), ('پرسپولیس', 1), ('سپاهان', 1), ('تیم ملی والیبال', 2), ('تیم ملی بسکتبال', 3), ('شهداب یزد', 2), ('مهرام', 3), ('تراکتور', 1), ('فولاد', 1), ('ذوب آهن', 1);


INSERT INTO venues (name, address, capacity, city_id) VALUES
('آزادی', 'تهران، خرگوش دره', 78000, 1),
('نقش جهان', 'اصفهان', 75000, 2),
('پارس', 'شیراز', 50000, 3),
('امام رضا', 'مشهد', 27000, 4),
('یادگار امام', 'تبریز', 70000, 5),
('فولاد آرنا', 'اهواز', 30000, 6),
('شهید وطنی', 'ساری', 15000, 7),
('سردار جنگل', 'رشت', 15000, 8),
('شهید باهنر', 'کرمان', 15000, 9),
('انقلاب', 'کرج', 15000, 10);


INSERT INTO users (first_name, last_name, phone_number, email, password_hash, is_active, role, city_id) VALUES
('علی', 'رضایی', '09121111111', 'ali@test.com', 'hash1', true, 'BUYER', 1),
('محمد', 'محمدی', '09122222222', 'mohammad@test.com', 'hash2', true, 'BUYER', 2),
('سارا', 'احمدی', '09123333333', 'sara@test.com', 'hash3', true, 'BUYER', 3),
('زهرا', 'کرمی', '09124444444', 'zahra@test.com', 'hash4', true, 'BUYER', 4),
('رضا', 'ردینگتون', '09125555555', 'reza@test.com', 'hash5', true, 'BUYER', 5),
('امید', 'نوری', '09126666666', 'omid@test.com', 'hash6', true, 'BUYER', 6),
('نیما', 'صادقی', '09127777777', 'nima@test.com', 'hash7', true, 'BUYER', 7),
('پشتیبان۱', 'سایت', '09128888888', 'sup1@test.com', 'hash8', true, 'SUPPORT', 1),
('پشتیبان۲', 'سایت', '09129999999', 'sup2@test.com', 'hash9', true, 'SUPPORT', 2),
('پشتیبان۳', 'سایت', '09130000000', 'sup3@test.com', 'hash10', true, 'SUPPORT', 3);


INSERT INTO seats (position_number, position_section, position_row_label, venue_id) VALUES
(1, 'A', 'R1', 1), (2, 'A', 'R1', 1), (3, 'A', 'R1', 1),
(1, 'B', 'R2', 2), (2, 'B', 'R2', 2), (3, 'B', 'R2', 2),
(1, 'C', 'R3', 3), (2, 'C', 'R3', 3), (3, 'C', 'R3', 3), (4, 'C', 'R3', 3);


INSERT INTO wallets (credit, user_id) VALUES
(100000, 1), (50000, 2), (0, 3), (200000, 4), (15000, 5),
(0, 6), (30000, 7), (0, 8), (0, 9), (0, 10);


INSERT INTO matches (datetime, status, host_team_id, guest_team_id, sport_id, tournament_id, venue_id) VALUES
('2026-08-01 18:00:00', 'SCHEDULED', 1, 2, 1, 1, 1),
('2026-08-02 18:00:00', 'ON_SALE', 3, 1, 1, 1, 2),
('2026-08-03 18:00:00', 'SOLD_OUT', 2, 3, 1, 1, 1),
('2026-08-04 18:00:00', 'IN_PROGRESS', 4, 6, 2, 1, 1),
('2026-08-05 18:00:00', 'FINISHED', 5, 7, 3, 1, 1),
('2026-08-06 18:00:00', 'CANCELLED', 8, 9, 1, 1, 5),
('2026-08-07 18:00:00', 'POSTPONED', 9, 10, 1, 1, 6),
('2026-08-08 18:00:00', 'SCHEDULED', 1, 3, 1, 2, 1),
('2026-08-09 18:00:00', 'SCHEDULED', 2, 8, 1, 2, 1),
('2026-08-10 18:00:00', 'SCHEDULED', 10, 1, 1, 2, 10);


INSERT INTO match_seats (price, status, match_id, seat_id, ticket_category_id) VALUES
(150000, 'AVAILABLE', 1, 1, 1),
(150000, 'RESERVED', 1, 2, 1),
(100000, 'SOLD', 1, 3, 3),
(200000, 'AVAILABLE', 2, 4, 1),
(200000, 'SOLD', 2, 5, 1),
(50000, 'BLOCKED', 3, 6, 3),
(120000, 'SOLD', 4, 7, 2),
(120000, 'AVAILABLE', 5, 8, 2),
(80000, 'RESERVED', 6, 9, 3),
(80000, 'SOLD', 7, 10, 3);


INSERT INTO reservations (reserved_at, expired_at, status, user_id) VALUES
('2026-07-20 10:00:00', '2026-07-20 10:15:00', 'CONFIRMED', 1),
('2026-07-21 11:00:00', '2026-07-21 11:15:00', 'CONFIRMED', 2),
('2026-07-22 12:00:00', '2026-07-22 12:15:00', 'CONFIRMED', 3),
('2026-07-23 13:00:00', '2026-07-23 13:15:00', 'CANCELLED', 4),
('2026-07-24 14:00:00', '2026-07-24 14:15:00', 'EXPIRED', 5),
('2026-07-25 15:00:00', '2026-07-25 15:15:00', 'PENDING', 6),
('2026-07-26 16:00:00', '2026-07-26 16:15:00', 'CONFIRMED', 7),
('2026-07-27 17:00:00', '2026-07-27 17:15:00', 'CONFIRMED', 1),
('2026-07-28 18:00:00', '2026-07-28 18:15:00', 'CONFIRMED', 2),
('2026-07-29 19:00:00', '2026-07-29 19:15:00', 'CONFIRMED', 3);


INSERT INTO reservation_items (price_at_time, match_seat_id, reservation_id) VALUES
(150000, 1, 1),
(150000, 2, 2),
(100000, 3, 3),
(200000, 4, 4),
(200000, 5, 5),
(50000, 6, 6),
(120000, 7, 7),
(120000, 8, 8),
(80000, 9, 9),
(80000, 10, 10);


INSERT INTO tickets (issued_at, used_at, ticket_code, qr_payload, status, reservation_item_id) VALUES
('2026-07-20 10:05:00', '2026-08-01 17:30:00', 'TCK-1001', 'QR1', 'USED', 1),
('2026-07-21 11:05:00', NULL, 'TCK-1002', 'QR2', 'ISSUED', 2),
('2026-07-22 12:05:00', NULL, 'TCK-1003', 'QR3', 'ISSUED', 3),
('2026-07-23 13:05:00', NULL, 'TCK-1004', 'QR4', 'CANCELLED', 4),
('2026-07-24 14:05:00', NULL, 'TCK-1005', 'QR5', 'EXPIRED', 5),
('2026-07-25 15:05:00', NULL, 'TCK-1006', 'QR6', 'ISSUED', 6),
('2026-07-26 16:05:00', NULL, 'TCK-1007', 'QR7', 'ISSUED', 7),
('2026-07-27 17:05:00', NULL, 'TCK-1008', 'QR8', 'ISSUED', 8),
('2026-07-28 18:05:00', NULL, 'TCK-1009', 'QR9', 'ISSUED', 9),
('2026-07-29 19:05:00', NULL, 'TCK-1010', 'QR10', 'ISSUED', 10);


INSERT INTO payments (amount, payment_date, transaction_ref, status, payment_method_id, reservation_id) VALUES
(150000, '2026-07-20 10:02:00', 'TRX-001', 'SUCCESS', 1, 1),
(150000, '2026-07-21 11:02:00', 'TRX-002', 'SUCCESS', 2, 2),
(100000, '2026-07-22 12:02:00', 'TRX-003', 'SUCCESS', 3, 3),
(200000, '2026-07-23 13:02:00', 'TRX-004', 'FAILED', 4, 4),
(200000, '2026-07-24 14:02:00', 'TRX-005', 'PENDING', 5, 5),
(50000, '2026-07-25 15:02:00', 'TRX-006', 'SUCCESS', 6, 6),
(120000, '2026-07-26 16:02:00', 'TRX-007', 'SUCCESS', 7, 7),
(120000, '2026-07-27 17:02:00', 'TRX-008', 'SUCCESS', 8, 8),
(80000, '2026-07-28 18:02:00', 'TRX-009', 'SUCCESS', 9, 9),
(80000, '2026-07-29 19:02:00', 'TRX-010', 'SUCCESS', 10, 10);


INSERT INTO cancellations (reason, requested_at, processed_at, status, reservation_id, user_id) VALUES
('تغییر برنامه', '2026-07-23 13:10:00', '2026-07-23 13:20:00', 'DONE', 4, 8),
('بیماری', '2026-07-21 11:30:00', '2026-07-21 12:00:00', 'REJECTED', 2, 9),
('اشتباه در خرید', '2026-07-24 14:10:00', NULL, 'PROCESSING', 5, 10),
('لغو بازی', '2026-07-28 18:10:00', '2026-07-28 18:15:00', 'DONE', 9, 8),
('مشکل شخصی', '2026-07-29 19:10:00', NULL, 'REQUESTED', 10, 9),
('عدم تمایل', '2026-07-20 10:30:00', '2026-07-20 11:00:00', 'DONE', 1, 8),
('خرید بلیط بهتر', '2026-07-22 12:30:00', '2026-07-22 13:00:00', 'APPROVED', 3, 9),
('دور بودن ورزشگاه', '2026-07-25 15:30:00', NULL, 'REQUESTED', 6, 10),
('عدم امکان حضور', '2026-07-26 16:30:00', '2026-07-26 17:00:00', 'DONE', 7, 8),
('دلیل نامشخص', '2026-07-27 17:30:00', '2026-07-27 18:00:00', 'REJECTED', 8, 9);


INSERT INTO issue_reports (subject, description, status, created_at, resolved_at, updated_at, user_id, payment_id) VALUES
('مشکل در پرداخت', 'پول کم شد ولی بلیط صادر نشد', 'CLOSED', '2026-07-23 13:05:00', '2026-07-23 14:00:00', '2026-07-23 14:00:00', 4, 11),
('کیفیت صندلی', 'صندلی خراب بود', 'OPEN', '2026-07-20 18:00:00', NULL, '2026-07-20 18:00:00', 1, 11),
('عدم دریافت پیامک', 'پیامک تایید نیامد', 'RESOLVED', '2026-07-21 12:00:00', '2026-07-21 12:30:00', '2026-07-21 12:30:00', 2, 12),
('خطای سیستم', 'سایت قطع شد', 'IN_PROGRESS', '2026-07-24 14:30:00', NULL, '2026-07-24 15:00:00', 5, 15),
('سوال درباره استرداد', 'چگونه کنسل کنم؟', 'CLOSED', '2026-07-25 10:00:00', '2026-07-25 10:15:00', '2026-07-25 10:15:00', 6, 16),
('مغایرت قیمت', 'قیمت بیشتر از سایت بود', 'OPEN', '2026-07-26 11:00:00', NULL, '2026-07-26 11:00:00', 7, 17),
('کنسلی مسابقه', 'تکلیف پول ما چه میشود؟', 'RESOLVED', '2026-07-27 12:00:00', '2026-07-27 13:00:00', '2026-07-27 13:00:00', 1, 18),
('مشکل ورود', 'بارکد خوانده نشد', 'CLOSED', '2026-07-28 13:00:00', '2026-07-28 14:00:00', '2026-07-28 14:00:00', 2, 19),
('تغییر صندلی', 'میخواهم جایم را عوض کنم', 'IN_PROGRESS', '2026-07-29 14:00:00', NULL, '2026-07-29 15:00:00', 3, 20),
('انتقاد از پشتیبانی', 'دیر جواب دادید', 'OPEN', '2026-07-22 15:00:00', NULL, '2026-07-22 15:00:00', 3, 13);


INSERT INTO logs (action, action_date, user_id) VALUES
('USER_LOGIN', '2026-07-20 09:00:00', 1),
('TICKET_PURCHASE', '2026-07-20 10:05:00', 1),
('USER_LOGIN', '2026-07-21 10:00:00', 2),
('PROFILE_UPDATE', '2026-07-21 10:10:00', 2),
('USER_LOGOUT', '2026-07-21 12:00:00', 2),
('PAYMENT_FAILED', '2026-07-23 13:02:00', 4),
('SUPPORT_TICKET_CREATED', '2026-07-23 13:05:00', 4),
('CANCELLATION_REQUESTED', '2026-07-24 14:10:00', 5),
('ADMIN_LOGIN', '2026-07-20 08:00:00', 8),
('ADMIN_RESOLVED_ISSUE', '2026-07-23 14:00:00', 8);

-- =============================================================== Informational And Analytical Queries ======================================================

--1
SELECT first_name,last_name
    FROM users
WHERE id NOT IN (SELECT user_id FROM reservations);

--2
SELECT DISTINCT u.first_name , u.last_name
FROM users u
JOIN reservations r ON u.id = r.user_id
JOIN reservation_items ri ON r.id = ri.reservation_id
JOIN tickets t ON ri.id = t.reservation_item_id;

--3
SELECT u.first_name, u.last_name,
       EXTRACT(YEAR FROM p.payment_date) AS pay_year,
       EXTRACT(MONTH FROM p.payment_date) AS pay_month,
       SUM(p.amount) AS total_paid
FROM payments p
JOIN reservations r ON p.reservation_id = r.id
JOIN users u ON r.user_id = u.id
GROUP BY u.id, u.first_name, u.last_name, pay_year, pay_month;

--4
SELECT u.first_name, u.last_name, c.name AS city_name
FROM users u
JOIN reservations r ON u.id = r.user_id
JOIN reservation_items ri ON r.id = ri.reservation_id
JOIN tickets t ON t.reservation_item_id = ri.id
JOIN match_seats ms ON ri.match_seat_id = ms.id
JOIN matches m ON ms.match_id = m.id
JOIN venues v ON m.venue_id = v.id
JOIN cities c ON v.city_id = c.id
GROUP BY u.id, u.first_name, u.last_name, c.id, c.name
HAVING COUNT(t.id) = 1;

--5
SELECT u.*
FROM tickets t
JOIN reservation_items ri ON t.reservation_item_id = ri.id
JOIN reservations r ON ri.reservation_id = r.id
JOIN users u ON r.user_id = u.id
ORDER BY t.issued_at DESC
LIMIT 1;

--6
SELECT u.phone, u.email
FROM users u
JOIN reservations r ON u.id = r.user_id
JOIN payments p ON r.id = p.reservation_id
GROUP BY u.id, u.phone, u.email
HAVING SUM(p.amount) > (SELECT AVG(total_paid) FROM (SELECT SUM(amount) AS total_paid FROM payments GROUP BY reservation_id) AS sub);

--7
SELECT s.name AS sport_name, COUNT(t.id) AS total_tickets
FROM sports s
JOIN matches m ON s.id = m.sport_id
JOIN match_seats ms ON m.id = ms.match_id
JOIN reservation_items ri ON ri.match_seat_id = ms.id
JOIN tickets t ON t.reservation_item_id = ri.id
GROUP BY s.id, s.name;

--8
SELECT u.first_name, u.last_name, COUNT(t.id) AS tickets_count
FROM users u
JOIN reservations r ON u.id = r.user_id
JOIN reservation_items ri ON r.id = ri.reservation_id
JOIN tickets t ON ri.id = t.reservation_item_id
WHERE t.issued_at >= CURRENT_DATE - INTERVAL '7 days'
GROUP BY u.id, u.first_name, u.last_name
ORDER BY tickets_count DESC
LIMIT 3;

--9
SELECT c.name AS city_name, COUNT(t.id) AS total_tickets
FROM cities c
JOIN venues v ON c.id = v.city_id
JOIN matches m ON v.id = m.venue_id
JOIN match_seats ms ON m.id = ms.match_id
JOIN reservation_items ri ON ri.match_seat_id = ms.id
JOIN tickets t ON t.reservation_item_id = ri.id
JOIN provinces p ON c.province_id = p.id
WHERE p.name = 'تهران'
GROUP BY c.id, c.name;

--10
SELECT DISTINCT c.name
FROM cities c
JOIN venues v ON c.id = v.city_id
JOIN matches m ON v.id = m.venue_id
JOIN match_seats ms ON m.id = ms.match_id
JOIN reservation_items ri ON ri.match_seat_id = ms.id
JOIN tickets t ON t.reservation_item_id = ri.id
JOIN reservations r ON ri.reservation_id = r.id
WHERE r.user_id = (SELECT id FROM users ORDER BY id ASC LIMIT 1);

--11
SELECT first_name, last_name
FROM users
WHERE role = 'SUPPORT';

--12
SELECT u.first_name, u.last_name
FROM users u
JOIN reservations r ON u.id = r.user_id
JOIN reservation_items ri ON r.id = ri.reservation_id
JOIN tickets t ON t.reservation_item_id = ri.id
GROUP BY u.id
HAVING COUNT(t.id) >= 2;

--13
SELECT u.first_name, u.last_name
FROM users u
JOIN reservations r ON u.id = r.user_id
JOIN reservation_items ri ON r.id = ri.reservation_id
JOIN tickets t ON t.reservation_item_id = ri.id
JOIN match_seats ms ON ri.match_seat_id = ms.id
JOIN matches m ON ms.match_id = m.id
JOIN sports s ON m.sport_id = s.id
WHERE s.name = 'فوتبال'
GROUP BY u.id, u.first_name, u.last_name
HAVING COUNT(t.id) <= 2;

--14
SELECT u.email, u.phone
FROM users u
JOIN reservations r ON u.id = r.user_id
JOIN reservation_items ri ON r.id = ri.reservation_id
JOIN tickets t ON t.reservation_item_id = ri.id
JOIN match_seats ms ON ri.match_seat_id = ms.id
JOIN matches m ON ms.match_id = m.id
JOIN sports s ON m.sport_id = s.id
WHERE s.name IN ('فوتبال', 'والیبال', 'بسکتبال')
GROUP BY u.id
HAVING COUNT(DISTINCT s.name) = 3;

--15
SELECT t.*
FROM tickets t
WHERE t.issued_at::date = CURRENT_DATE
ORDER BY t.issued_at ASC;

--16
SELECT ms.id, COUNT(t.id) AS sales_count
FROM tickets t
JOIN match_seats ms ON t.reservation_item_id = ms.id
GROUP BY ms.id
ORDER BY sales_count DESC
OFFSET 1 LIMIT 1;

--17
SELECT
    u.first_name,
    u.last_name,
    COUNT(c.id) AS total_cancellations_by_support,
    ROUND((COUNT(c.id) * 100.0 / NULLIF((SELECT COUNT(*) FROM cancellations), 0)), 2) AS cancellation_percentage
FROM users u
JOIN cancellations c ON u.id = c.user_id
WHERE u.role = 'SUPPORT'
GROUP BY u.id, u.first_name, u.last_name
ORDER BY total_cancellations_by_support DESC
LIMIT 1;

--18
UPDATE users
SET last_name = 'ردینگتون'
WHERE id = (SELECT u.id FROM users u JOIN cancellations c ON u.id = c.user_id
            GROUP BY u.id ORDER BY COUNT(c.id) DESC LIMIT 1);

--19
DELETE FROM tickets
WHERE reservation_item_id IN (
    SELECT ri.id
    FROM reservation_items ri
    JOIN cancellations c ON ri.reservation_id = c.reservation_id
    JOIN users u ON c.user_id = u.id
    WHERE u.last_name = 'ردینگتون'
    );

--20
DELETE FROM tickets
WHERE id IN (SELECT t.id FROM tickets t WHERE t.status = 'CANCELLED');

--21
UPDATE match_seats ms
SET price = price * 0.9
FROM matches m
JOIN venues v ON m.venue_id = v.id
WHERE ms.match_id = m.id AND v.name = 'آزادی'
AND m.datetime::date = CURRENT_DATE - INTERVAL '1 day';

--22
SELECT subject, COUNT(*) AS report_count
FROM issue_reports
GROUP BY subject
ORDER BY report_count DESC
LIMIT 1;


--=========================================================== Stored Procedures Queries ========================================================


--1
CREATE OR REPLACE FUNCTION get_user_tickets(p_identifier VARCHAR)
RETURNS TABLE (ticket_id BIGINT, ticket_code VARCHAR, issued_at TIMESTAMP) AS $$
BEGIN
    RETURN QUERY
    SELECT t.id, t.ticket_code, t.issued_at
    FROM users u
    JOIN reservations r ON u.id = r.user_id
    JOIN reservation_items ri ON r.id = ri.reservation_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    WHERE u.email = p_identifier OR u.phone = p_identifier
    ORDER BY t.issued_at ASC;
END;
$$ LANGUAGE plpgsql;

--2
CREATE OR REPLACE FUNCTION get_canceled_users_by_support(p_support_identifier VARCHAR)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT buyer.first_name, buyer.last_name
    FROM users support_agent
    JOIN cancellations c ON support_agent.id = c.user_id
    JOIN reservations r ON c.reservation_id = r.id
    JOIN users buyer ON r.user_id = buyer.id
    WHERE (support_agent.email = p_support_identifier OR support_agent.phone = p_support_identifier)
      AND support_agent.role = 'SUPPORT';
END;
$$ LANGUAGE plpgsql;


--3
CREATE OR REPLACE FUNCTION get_tickets_by_city(p_city_name VARCHAR)
RETURNS TABLE (ticket_code VARCHAR, match_datetime TIMESTAMP) AS $$
BEGIN
    RETURN QUERY
    SELECT t.ticket_code, m.datetime
    FROM cities c
    JOIN venues v ON c.id = v.city_id
    JOIN matches m ON v.id = m.venue_id
    JOIN match_seats ms ON m.id = ms.match_id
    JOIN reservation_items ri ON ms.id = ri.match_seat_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    WHERE c.name = p_city_name;
END;
$$ LANGUAGE plpgsql;

--4
CREATE OR REPLACE FUNCTION search_tickets(p_phrase VARCHAR)
RETURNS TABLE (ticket_code VARCHAR, user_name VARCHAR, venue_name VARCHAR) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT t.ticket_code, u.first_name || ' ' || u.last_name, v.name
    FROM tickets t
    JOIN reservation_items ri ON t.reservation_item_id = ri.id
    JOIN reservations r ON ri.reservation_id = r.id
    JOIN users u ON r.user_id = u.id
    JOIN match_seats ms ON ri.match_seat_id = ms.id
    JOIN matches m ON ms.match_id = m.id
    JOIN venues v ON m.venue_id = v.id
    JOIN teams ht ON m.host_team_id = ht.id
    JOIN teams gt ON m.guest_team_id = gt.id
    JOIN ticket_categories tc ON ms.ticket_category_id = tc.id
    WHERE u.first_name ILIKE '%' || p_phrase || '%'
       OR u.last_name ILIKE '%' || p_phrase || '%'
       OR v.name ILIKE '%' || p_phrase || '%'
       OR ht.name ILIKE '%' || p_phrase || '%'
       OR gt.name ILIKE '%' || p_phrase || '%'
       OR tc.name ILIKE '%' || p_phrase || '%';
END;
$$ LANGUAGE plpgsql;

--5
CREATE OR REPLACE FUNCTION get_same_city_users(p_identifier VARCHAR)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR, email VARCHAR) AS $$
BEGIN
    RETURN QUERY
    SELECT other.first_name, other.last_name, other.email
    FROM users target_user
    JOIN users other ON target_user.city_id = other.city_id
    WHERE (target_user.email = p_identifier OR target_user.phone = p_identifier)
      AND other.id != target_user.id;
END;
$$ LANGUAGE plpgsql;

--6
CREATE OR REPLACE FUNCTION get_top_buyers_since(p_date TIMESTAMP, p_limit INT)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR, total_tickets BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT u.first_name, u.last_name, COUNT(t.id) AS t_count
    FROM users u
    JOIN reservations r ON u.id = r.user_id
    JOIN reservation_items ri ON r.id = ri.reservation_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    WHERE t.issued_at >= p_date
    GROUP BY u.id, u.first_name, u.last_name
    ORDER BY t_count DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

--7
CREATE OR REPLACE FUNCTION get_canceled_tickets_by_sport(p_sport_name VARCHAR)
RETURNS TABLE (ticket_code VARCHAR, requested_at TIMESTAMP) AS $$
BEGIN
    RETURN QUERY
    SELECT t.ticket_code, c.requested_at
    FROM sports s
    JOIN matches m ON s.id = m.sport_id
    JOIN match_seats ms ON m.id = ms.match_id
    JOIN reservation_items ri ON ms.id = ri.match_seat_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    JOIN reservations r ON ri.reservation_id = r.id
    JOIN cancellations c ON r.id = c.reservation_id
    WHERE s.name = p_sport_name
    ORDER BY c.requested_at ASC;
END;
$$ LANGUAGE plpgsql;

--8
CREATE OR REPLACE FUNCTION get_top_reporters_by_subject(p_subject VARCHAR)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR, report_count BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT u.first_name, u.last_name, COUNT(ir.id) AS r_count
    FROM users u
    JOIN issue_reports ir ON u.id = ir.user_id
    WHERE ir.subject = p_subject
    GROUP BY u.id, u.first_name, u.last_name
    ORDER BY r_count DESC;
END;
$$ LANGUAGE plpgsql;



-- Index on email and phone to speed up user searches (used in functions 1, 2, and 5)
CREATE INDEX idx_users_email_phone ON users(email, phone);

-- Index on city name to speed up filtering by city (used in function 3)
CREATE INDEX idx_cities_name ON cities(name);

-- Index on ticket issuance date to speed up date range queries (used in function 6)
CREATE INDEX idx_tickets_issued_at ON tickets(issued_at);

-- Index on support issue reports subject (used in function 8)
CREATE INDEX idx_issue_reports_subject ON issue_reports(subject);



