-- ================================================================== Creating Database =====================================================================
-- Uncomment the following lines if you need to create the database from scratch
-- CREATE DATABASE pitchside_db;
-- \c pitchside_db;

-- ================================================================== Creating Tables ======================================================================== 

create table payment_methods
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255) not null,
    status      varchar(255) not null
        constraint payment_methods_status_check
            check ((status)::text = ANY
        ((ARRAY ['ALLOWED'::character varying, 'NOT_ALLOWED'::character varying])::text[]))
    );

alter table payment_methods owner to postgres;

create table provinces
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table provinces owner to postgres;

create table cities
(
    id          bigint generated by default as identity
        primary key,
    province_id bigint       not null
        constraint fkcf2ndxcsekl26rrkb9egbhq20 references provinces,
    name        varchar(255) not null
);

alter table cities owner to postgres;

create table sports
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table sports owner to postgres;

create table teams
(
    id       bigint generated by default as identity
        primary key,
    sport_id bigint       not null
        constraint fkc2kpkonbxgprdwilacrp2tkp8 references sports,
    name     varchar(255) not null
);

alter table teams owner to postgres;

create table ticket_categories
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255) not null,
    amenities jsonb
);

alter table ticket_categories owner to postgres;

create table tournaments
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table tournaments owner to postgres;

create table users
(
    is_active     boolean      not null,
    city_id       bigint       not null
        constraint fkn36jwt4acj3il2ixvv2c0ncco references cities,
    id            bigint generated by default as identity
        primary key,
    email         varchar(255) not null,
    first_name    varchar(255) not null,
    last_name     varchar(255) not null,
    password_hash varchar(255) not null,
    phone         varchar(255) not null
        constraint chk_user_phone check ((phone)::text ~ '^(09|9)[0-9]{9}$'::text),
    role          varchar(255) not null
        constraint users_role_check check ((role)::text = ANY ((ARRAY ['BUYER'::character varying, 'SUPPORT'::character varying])::text[])),
    login_method  varchar(20)  default 'EMAIL' not null
        constraint users_login_method_check check ((login_method)::text = ANY ((ARRAY ['EMAIL'::character varying, 'PHONE'::character varying])::text[]))
);

alter table users owner to postgres;

create table logs
(
    action_date timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    user_id     bigint       not null
        constraint fkgqy8beil5y4almtq1tiyofije references users,
    action      varchar(255) not null
);

alter table logs owner to postgres;

create table reservations
(
    expired_at  timestamp(6),
    id          bigint generated by default as identity
        primary key,
    reserved_at timestamp(6) not null,
    user_id     bigint       not null
        constraint fkb5g9io5h54iwl2inkno50ppln references users,
    status      varchar(255) not null
        constraint reservations_status_check check ((status)::text = ANY ((ARRAY ['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])),
    constraint chk_reservation_dates check ((expired_at IS NULL) OR (reserved_at <= expired_at))
);

alter table reservations owner to postgres;

create table cancellations
(
    id             bigint generated by default as identity
        primary key,
    processed_at   timestamp(6),
    requested_at   timestamp(6) not null,
    reservation_id bigint       not null
        unique constraint fkagn8cqvm03koa4w6pdn1pxvcn references reservations,
    user_id        bigint       not null
        constraint fk33w7524mgghj8pnfu2om1aave references users,
    reason         text         not null,
    status         varchar(255) not null
        constraint cancellations_status_check check ((status)::text = ANY ((ARRAY ['REQUESTED'::character varying, 'PROCESSING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'DONE'::character varying])::text[])),
    constraint chk_cancellation_dates check ((processed_at IS NULL) OR (requested_at <= processed_at))
);

alter table cancellations owner to postgres;

create table payments
(
    amount            numeric(19, 2) not null,
    id                bigint generated by default as identity
        primary key,
    payment_date      timestamp(6)   not null,
    payment_method_id bigint         not null
        constraint fkce1n8pa67lq4l57l9mhugdgab references payment_methods,
    reservation_id    bigint         not null
        constraint fkp8yh4sjt3u0g6aru1oxfh3o14 references reservations,
    status            varchar(255)   not null
        constraint payments_status_check check ((status)::text = ANY ((ARRAY ['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])),
    transaction_ref   varchar(255) unique
);

alter table payments owner to postgres;

create table issue_reports
(
    created_at  timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    payment_id  bigint
        constraint fk4u2nabh6tcct29r73p0b6bvey references payments,
    resolved_at timestamp(6),
    updated_at  timestamp(6),
    user_id     bigint
        constraint fkh1b3ubh9t7f8quo02v7rx91s7 references users,
    description text         not null,
    status      varchar(255) not null
        constraint issue_reports_status_check check ((status)::text = ANY ((ARRAY ['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])),
    subject     varchar(255) not null,
    constraint chk_issue_dates check (((resolved_at IS NULL) OR (created_at <= resolved_at)) AND ((updated_at IS NULL) OR (created_at <= updated_at)))
);

alter table issue_reports owner to postgres;

create table venues
(
    capacity integer      not null
        constraint chk_venue_capacity check (capacity > 0),
    city_id  bigint       not null
        constraint fkm3mi79lpgax9ln1v2kbrc9fsb references cities,
    id       bigint generated by default as identity
        primary key,
    address  varchar(255) not null,
    name     varchar(255) not null
);

alter table venues owner to postgres;

create table matches
(
    datetime      timestamp(6) not null,
    guest_team_id bigint       not null
        constraint fkn9oyy00pityvaekt35sia05cv references teams,
    host_team_id  bigint       not null
        constraint fk7b3141h0f8f6qtqhsqqlh6rjy references teams,
    id            bigint generated by default as identity
        primary key,
    sport_id      bigint       not null
        constraint fklo85d6syiegp2utk9l2vewxq5 references sports,
    tournament_id bigint       not null
        constraint fkeeniokyjgo5k6rmhjujatn27i references tournaments,
    venue_id      bigint       not null
        constraint fkgfd82fqocrak8cp07iegd68fn references venues,
    status        varchar(255) not null
        constraint matches_status_check check ((status)::text = ANY ((ARRAY ['SCHEDULED'::character varying, 'ON_SALE'::character varying, 'SOLD_OUT'::character varying, 'IN_PROGRESS'::character varying, 'FINISHED'::character varying, 'CANCELLED'::character varying, 'POSTPONED'::character varying])::text[]))
    );

alter table matches owner to postgres;

create table seats
(
    position_number    integer      not null
        constraint chk_seat_number check (position_number > 0),
    id                 bigint generated by default as identity
        primary key,
    venue_id           bigint       not null
        constraint fkfahhtb0bb0u1wcnqqys0iehmo references venues,
    position_row_label varchar(255) not null,
    position_section   varchar(255) not null
);

alter table seats owner to postgres;

create table match_seats
(
    price              numeric(38, 2) not null
        constraint chk_seat_price check (price >= (0)::numeric),
    id                 bigint generated by default as identity
        primary key,
    match_id           bigint         not null
        constraint fkll740wd2td5wp4bth0jwtk12l references matches,
    seat_id            bigint         not null
        constraint fknf0ykdil4auidynaq25bvopc5 references seats,
    ticket_category_id bigint         not null
        constraint fktfxdjbi6cwbtubs6y55wayor references ticket_categories,
    status             varchar(255)   not null
        constraint match_seats_status_check check ((status)::text = ANY ((ARRAY ['AVAILABLE'::character varying, 'RESERVED'::character varying, 'SOLD'::character varying, 'BLOCKED'::character varying])::text[]))
);

alter table match_seats owner to postgres;

create table reservation_items
(
    price_at_time  numeric(19, 2) not null
        constraint chk_price_at_time check (price_at_time >= (0)::numeric),
    id             bigint generated by default as identity
        primary key,
    match_seat_id  bigint         not null
        constraint fkth8dqkmcf8o7fg70nl8v0ktv9 references match_seats,
    reservation_id bigint         not null
        constraint fkahatpyi4mk3o5dcqt7d51r31k references reservations
);

alter table reservation_items owner to postgres;

create table tickets
(
    id                  bigint generated by default as identity
        primary key,
    issued_at           timestamp(6) not null,
    reservation_item_id bigint       not null
        unique constraint fk7e6s7gu134q0jfek19r78pwpm references reservation_items,
    used_at             timestamp(6),
    ticket_code         varchar(50)  not null unique,
    qr_payload          text,
    status              varchar(255) not null
        constraint tickets_status_check check ((status)::text = ANY ((ARRAY ['ISSUED'::character varying, 'USED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])),
    constraint chk_ticket_dates check ((used_at IS NULL) OR (issued_at <= used_at))
);

alter table tickets owner to postgres;

create table wallets
(
    credit  numeric(19, 2) not null
        constraint chk_wallet_credit check (credit >= (0)::numeric),
    id      bigint generated by default as identity
        primary key,
    user_id bigint         not null
        unique constraint fkc1foyisidw7wqqrkamafuwn4e references users
);

alter table wallets owner to postgres;


-- ==================================================================== Inserting Data Queries ===============================================================

-- 1. Sports
INSERT INTO sports (name) VALUES ('Football'), ('Basketball'), ('Volleyball');

-- 2. Ticket Categories (No Student)
-- 1:VVIP, 2:VIP, 3:Regular, 4:Premium, 5:Economy, 6:Family, 7:Disabled, 8:Early Bird, 9:Last Minute
INSERT INTO ticket_categories (name, amenities) VALUES
                                                    ('VVIP', '{"parking": true, "food": true, "lounge": true}'),
                                                    ('VIP', '{"parking": true, "food": true}'),
                                                    ('Regular', '{"parking": false, "food": false}'),
                                                    ('Premium', '{"parking": true, "food": false}'),
                                                    ('Economy', '{}'),
                                                    ('Family', '{"kid_zone": true}'),
                                                    ('Disabled', '{"wheelchair_access": true}'),
                                                    ('Early Bird', '{}'),
                                                    ('Last Minute', '{}');

-- 3. Provinces
INSERT INTO provinces (name) VALUES
                                 ('England'), ('Spain'), ('Italy'), ('Germany'), ('France'), ('USA'), ('Poland');

-- 4. Cities
INSERT INTO cities (name, province_id) VALUES
                                           ('London', 1), ('Manchester', 1), ('Madrid', 2), ('Barcelona', 2),
                                           ('Milan', 3), ('Turin', 3), ('Munich', 4), ('Paris', 5),
                                           ('Los Angeles', 6), ('Warsaw', 7);

-- 5. Payment Methods (Kept in Persian as requested, Statuses updated to match constraint)
INSERT INTO payment_methods (description, status) VALUES
                                                      ('درگاه ملت', 'ALLOWED'),
                                                      ('درگاه سامان', 'ALLOWED'),
                                                      ('درگاه ملی', 'NOT_ALLOWED'),
                                                      ('کارت به کارت', 'ALLOWED'),
                                                      ('کیف پول', 'ALLOWED'),
                                                      ('پرداخت در محل', 'NOT_ALLOWED'),
                                                      ('درگاه پاسارگاد', 'ALLOWED'),
                                                      ('زرین پال', 'ALLOWED');

-- 6. Tournaments (10 Leagues)
INSERT INTO tournaments (name) VALUES
                                   ('Premier League'), ('La Liga'), ('Serie A'), ('Bundesliga'), ('Ligue 1'),
                                   ('NBA'), ('Liga ACB'), ('Lega Basket Serie A'),
                                   ('SuperLega'), ('PlusLiga');

-- 7. Teams (4 Teams per League = 40 Teams)
-- Football
INSERT INTO teams (name, sport_id) VALUES
                                       ('Arsenal', 1), ('Chelsea', 1), ('Manchester City', 1), ('Liverpool', 1),
                                       ('Real Madrid', 1), ('Barcelona', 1), ('Atletico Madrid', 1), ('Sevilla', 1),
                                       ('AC Milan', 1), ('Inter Milan', 1), ('Juventus', 1), ('Napoli', 1),
                                       ('Bayern Munich', 1), ('Borussia Dortmund', 1), ('RB Leipzig', 1), ('Bayer Leverkusen', 1),
                                       ('Paris Saint-Germain', 1), ('Marseille', 1), ('Lyon', 1), ('AS Monaco', 1);

-- Basketball
INSERT INTO teams (name, sport_id) VALUES
                                       ('Los Angeles Lakers', 2), ('Golden State Warriors', 2), ('Boston Celtics', 2), ('Chicago Bulls', 2),
                                       ('Real Madrid Basketball', 2), ('FC Barcelona Basquet', 2), ('Baskonia', 2), ('Valencia Basket', 2),
                                       ('Olimpia Milano', 2), ('Virtus Bologna', 2), ('Reyer Venezia', 2), ('Dinamo Sassari', 2);

-- Volleyball
INSERT INTO teams (name, sport_id) VALUES
                                       ('Trentino Volley', 3), ('Sir Safety Perugia', 3), ('Lube Volley', 3), ('Gas Sales Piacenza', 3),
                                       ('ZAKSA Kedzierzyn-Kozle', 3), ('Jastrzebski Wegiel', 3), ('Asseco Resovia', 3), ('Projekt Warszawa', 3);

-- 8. Venues (1 Venue per League)
INSERT INTO venues (name, address, capacity, city_id) VALUES
                                                          ('Emirates', 'London, Hornsey Road', 60000, 1),
                                                          ('Santiago Bernabeu', 'Madrid, Chamartin', 81000, 3),
                                                          ('San Siro', 'Milan, San Siro District', 75000, 5),
                                                          ('Allianz Arena', 'Munich, Werner-Heisenberg-Allee', 75000, 7),
                                                          ('Parc des Princes', 'Paris, 16th arrondissement', 47000, 8),
                                                          ('Crypto.com Arena', 'Los Angeles, Downtown', 19000, 9),
                                                          ('WiZink Center', 'Madrid, Salamanca neighborhood', 15000, 3),
                                                          ('Mediolanum Forum', 'Milan, Assago', 12000, 5),
                                                          ('PalaAlpitour', 'Turin, Santa Rita', 14000, 6),
                                                          ('Torwar Hall', 'Warsaw, City Center', 4000, 10);

-- 9. Users
INSERT INTO users (first_name, last_name, phone, email, password_hash, is_active, role, city_id, login_method) VALUES
                                                                                                                   ('Ali', 'Rezaei', '09121111111', 'ali@test.com', 'hash1', true, 'BUYER', 1, 'EMAIL'),
                                                                                                                   ('Mohammad', 'Mohammadi', '09122222222', 'mohammad@test.com', 'hash2', true, 'BUYER', 2, 'EMAIL'),
                                                                                                                   ('Sara', 'Ahmadi', '09123333333', 'sara@test.com', 'hash3', true, 'BUYER', 3, 'PHONE'),
                                                                                                                   ('Zahra', 'Karami', '09124444444', 'zahra@test.com', 'hash4', true, 'BUYER', 4, 'EMAIL'),
                                                                                                                   ('Reza', 'Reddington', '09125555555', 'reza@test.com', 'hash5', true, 'BUYER', 5, 'PHONE'),
                                                                                                                   ('Omid', 'Nouri', '09126666666', 'omid@test.com', 'hash6', true, 'BUYER', 6, 'EMAIL'),
                                                                                                                   ('Nima', 'Sadeghi', '09127777777', 'nima@test.com', 'hash7', true, 'BUYER', 7, 'PHONE'),
                                                                                                                   ('Support1', 'Site', '09128888888', 'sup1@test.com', 'hash8', true, 'SUPPORT', 1, 'EMAIL'),
                                                                                                                   ('Support2', 'Site', '09129999999', 'sup2@test.com', 'hash9', true, 'SUPPORT', 2, 'EMAIL'),
                                                                                                                   ('Support3', 'Site', '09130000000', 'sup3@test.com', 'hash10', true, 'SUPPORT', 3, 'EMAIL');

INSERT INTO wallets (credit, user_id) VALUES
                                          (100000, 1), (50000, 2), (0, 3), (200000, 4), (15000, 5),
                                          (0, 6), (30000, 7), (0, 8), (0, 9), (0, 10);

-- 10. Generate Seats (80 Seats per Venue: 8 Sections * 10 Seats) = 800 Seats total
INSERT INTO seats (venue_id, position_section, position_row_label, position_number)
SELECT
    v.id AS venue_id,
    sec.name AS position_section,
    'R' || ceil(num.n / 5.0) AS position_row_label,
    num.n AS position_number
FROM venues v
         CROSS JOIN (
    VALUES ('n-lower'), ('s-lower'), ('w-lower'), ('e-lower'),
           ('n-upper'), ('s-upper'), ('w-upper'), ('e-upper')
) AS sec(name)
         CROSS JOIN (
    VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10)
) AS num(n);

-- 11. Matches (2 Matches per Tournament = 20 Matches)
INSERT INTO matches (datetime, status, host_team_id, guest_team_id, sport_id, tournament_id, venue_id) VALUES
-- Premier League
('2026-08-15 20:00:00', 'SCHEDULED', 1, 2, 1, 1, 1), ('2026-08-22 18:00:00', 'ON_SALE', 3, 4, 1, 1, 1),
-- La Liga
('2026-08-16 21:00:00', 'SCHEDULED', 5, 6, 1, 2, 2), ('2026-08-23 19:00:00', 'ON_SALE', 7, 8, 1, 2, 2),
-- Serie A
('2026-08-17 20:30:00', 'SCHEDULED', 9, 10, 1, 3, 3), ('2026-08-24 18:30:00', 'ON_SALE', 11, 12, 1, 3, 3),
-- Bundesliga
('2026-08-18 15:30:00', 'SCHEDULED', 13, 14, 1, 4, 4), ('2026-08-25 15:30:00', 'ON_SALE', 15, 16, 1, 4, 4),
-- Ligue 1
('2026-08-19 21:00:00', 'SCHEDULED', 17, 18, 1, 5, 5), ('2026-08-26 21:00:00', 'ON_SALE', 19, 20, 1, 5, 5),
-- NBA
('2026-10-15 19:00:00', 'SCHEDULED', 21, 22, 2, 6, 6), ('2026-10-22 19:00:00', 'ON_SALE', 23, 24, 2, 6, 6),
-- Liga ACB
('2026-09-15 18:00:00', 'SCHEDULED', 25, 26, 2, 7, 7), ('2026-09-22 18:00:00', 'ON_SALE', 27, 28, 2, 7, 7),
-- Lega Basket
('2026-09-16 20:00:00', 'SCHEDULED', 29, 30, 2, 8, 8), ('2026-09-23 20:00:00', 'ON_SALE', 31, 32, 2, 8, 8),
-- SuperLega
('2026-10-10 18:00:00', 'SCHEDULED', 33, 34, 3, 9, 9), ('2026-10-17 18:00:00', 'ON_SALE', 35, 36, 3, 9, 9),
-- PlusLiga
('2026-10-11 17:30:00', 'SCHEDULED', 37, 38, 3, 10, 10), ('2026-10-18 17:30:00', 'ON_SALE', 39, 40, 3, 10, 10);

-- 12. Generate Match Seats (20 Matches * 80 Seats = 1600 Match Seats dynamically generated)
INSERT INTO match_seats (price, status, match_id, seat_id, ticket_category_id)
SELECT
    -- Price generation based on section
    CASE
        WHEN s.position_section = 'n-lower' THEN 250000
        WHEN s.position_section = 's-lower' THEN 250000
        WHEN s.position_section IN ('w-lower', 'e-lower') THEN 150000
        WHEN s.position_section IN ('n-upper', 's-upper') THEN 80000
        ELSE 60000
        END AS price,
    -- Status pseudo-randomization to look realistic
    CASE
        WHEN (s.id + m.id) % 7 = 0 THEN 'SOLD'
        WHEN (s.id + m.id) % 13 = 0 THEN 'RESERVED'
        WHEN (s.id + m.id) % 17 = 0 THEN 'BLOCKED'
        ELSE 'AVAILABLE'
        END AS status,
    m.id AS match_id,
    s.id AS seat_id,
    -- Category mapping perfectly matching the Frontend React Code
    CASE
        WHEN s.position_section = 'n-lower' AND s.position_number <= 4 THEN 1 -- VVIP
        WHEN s.position_section = 'n-lower' THEN 4 -- Premium
        WHEN s.position_section = 's-lower' AND s.position_number <= 5 THEN 2 -- VIP
        WHEN s.position_section = 's-lower' THEN 6 -- Family
        WHEN s.position_section = 'w-lower' AND s.position_number <= 2 THEN 7 -- Disabled
        WHEN s.position_section = 'w-lower' THEN 3 -- Regular
        WHEN s.position_section = 'e-lower' AND s.position_number <= 5 THEN 4 -- Premium
        WHEN s.position_section = 'e-lower' THEN 8 -- Early Bird
        WHEN s.position_section IN ('n-upper', 's-upper', 'e-upper') THEN 5 -- Economy
        WHEN s.position_section = 'w-upper' AND s.position_number <= 3 THEN 9 -- Last Minute
        ELSE 3 -- Regular
        END AS ticket_category_id
FROM matches m
         JOIN seats s ON m.venue_id = s.venue_id;

-- 13. Mock Transactions for Analytic Queries (Mapped to the first few Match Seats)
INSERT INTO reservations (reserved_at, expired_at, status, user_id) VALUES
                                                                        ('2026-07-20 10:00:00', '2026-07-20 10:15:00', 'CONFIRMED', 1),
                                                                        ('2026-07-21 11:00:00', '2026-07-21 11:15:00', 'CONFIRMED', 2),
                                                                        ('2026-07-22 12:00:00', '2026-07-22 12:15:00', 'CONFIRMED', 3),
                                                                        ('2026-07-23 13:00:00', '2026-07-23 13:15:00', 'CANCELLED', 4),
                                                                        ('2026-07-24 14:00:00', '2026-07-24 14:15:00', 'EXPIRED', 5);

INSERT INTO reservation_items (price_at_time, match_seat_id, reservation_id) VALUES
                                                                                 (250000, 1, 1), (250000, 2, 2), (150000, 3, 3), (200000, 4, 4), (200000, 5, 5);

INSERT INTO tickets (issued_at, used_at, ticket_code, qr_payload, status, reservation_item_id) VALUES
                                                                                                   ('2026-07-20 10:05:00', '2026-08-01 17:30:00', 'TCK-1001', 'QR1', 'USED', 1),
                                                                                                   ('2026-07-21 11:05:00', NULL, 'TCK-1002', 'QR2', 'ISSUED', 2),
                                                                                                   ('2026-07-22 12:05:00', NULL, 'TCK-1003', 'QR3', 'ISSUED', 3),
                                                                                                   ('2026-07-23 13:05:00', NULL, 'TCK-1004', 'QR4', 'CANCELLED', 4),
                                                                                                   ('2026-07-24 14:05:00', NULL, 'TCK-1005', 'QR5', 'EXPIRED', 5);

INSERT INTO payments (amount, payment_date, transaction_ref, status, payment_method_id, reservation_id) VALUES
                                                                                                            (250000, '2026-07-20 10:02:00', 'TRX-001', 'SUCCESS', 1, 1),
                                                                                                            (250000, '2026-07-21 11:02:00', 'TRX-002', 'SUCCESS', 2, 2),
                                                                                                            (150000, '2026-07-22 12:02:00', 'TRX-003', 'SUCCESS', 3, 3),
                                                                                                            (200000, '2026-07-23 13:02:00', 'TRX-004', 'FAILED', 4, 4),
                                                                                                            (200000, '2026-07-24 14:02:00', 'TRX-005', 'PENDING', 5, 5);

INSERT INTO cancellations (reason, requested_at, processed_at, status, reservation_id, user_id) VALUES
    ('Schedule change', '2026-07-23 13:10:00', '2026-07-23 13:20:00', 'DONE', 4, 8);

INSERT INTO issue_reports (subject, description, status, created_at, resolved_at, updated_at, user_id, payment_id) VALUES
                                                                                                                       ('Payment Issue', 'Money deducted but ticket not issued', 'CLOSED', '2026-07-23 13:05:00', '2026-07-23 14:00:00', '2026-07-23 14:00:00', 4, 4),
                                                                                                                       ('Seat Quality', 'Seat was broken', 'OPEN', '2026-07-20 18:00:00', NULL, '2026-07-20 18:00:00', 1, 1);

INSERT INTO logs (action, action_date, user_id) VALUES
                                                    ('USER_LOGIN', '2026-07-20 09:00:00', 1), ('TICKET_PURCHASE', '2026-07-20 10:05:00', 1);

--=========================================================== Stored Procedures Queries ========================================================
-- [Database Functions and Indexes remain identical as previous]
--=========================================================== Stored Procedures Queries ========================================================


--1
CREATE OR REPLACE FUNCTION get_user_tickets(p_identifier VARCHAR)
RETURNS TABLE (ticket_id BIGINT, ticket_code VARCHAR, issued_at TIMESTAMP) AS $$
BEGIN
    RETURN QUERY
    SELECT t.id, t.ticket_code, t.issued_at
    FROM users u
    JOIN reservations r ON u.id = r.user_id
    JOIN reservation_items ri ON r.id = ri.reservation_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    WHERE u.email = p_identifier OR u.phone = p_identifier
    ORDER BY t.issued_at ASC;
END;
$$ LANGUAGE plpgsql;[cite: 2]

--2
CREATE OR REPLACE FUNCTION get_canceled_users_by_support(p_support_identifier VARCHAR)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT buyer.first_name, buyer.last_name
    FROM users support_agent
    JOIN cancellations c ON support_agent.id = c.user_id
    JOIN reservations r ON c.reservation_id = r.id
    JOIN users buyer ON r.user_id = buyer.id
    WHERE (support_agent.email = p_support_identifier OR support_agent.phone = p_support_identifier)
      AND support_agent.role = 'SUPPORT';
END;
$$ LANGUAGE plpgsql;[cite: 2]


--3
CREATE OR REPLACE FUNCTION get_tickets_by_city(p_city_name VARCHAR)
RETURNS TABLE (ticket_code VARCHAR, match_datetime TIMESTAMP) AS $$
BEGIN
    RETURN QUERY
    SELECT t.ticket_code, m.datetime
    FROM cities c
    JOIN venues v ON c.id = v.city_id
    JOIN matches m ON v.id = m.venue_id
    JOIN match_seats ms ON m.id = ms.match_id
    JOIN reservation_items ri ON ms.id = ri.match_seat_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    WHERE c.name = p_city_name;
END;
$$ LANGUAGE plpgsql;[cite: 2]

--4
CREATE OR REPLACE FUNCTION search_tickets(p_phrase VARCHAR)
RETURNS TABLE (ticket_code VARCHAR, user_name VARCHAR, venue_name VARCHAR) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT t.ticket_code, u.first_name || ' ' || u.last_name, v.name
    FROM tickets t
    JOIN reservation_items ri ON t.reservation_item_id = ri.id
    JOIN reservations r ON ri.reservation_id = r.id
    JOIN users u ON r.user_id = u.id
    JOIN match_seats ms ON ri.match_seat_id = ms.id
    JOIN matches m ON ms.match_id = m.id
    JOIN venues v ON m.venue_id = v.id
    JOIN teams ht ON m.host_team_id = ht.id
    JOIN teams gt ON m.guest_team_id = gt.id
    JOIN ticket_categories tc ON ms.ticket_category_id = tc.id
    WHERE u.first_name ILIKE '%' || p_phrase || '%'
       OR u.last_name ILIKE '%' || p_phrase || '%'
       OR v.name ILIKE '%' || p_phrase || '%'
       OR ht.name ILIKE '%' || p_phrase || '%'
       OR gt.name ILIKE '%' || p_phrase || '%'
       OR tc.name ILIKE '%' || p_phrase || '%';
END;
$$ LANGUAGE plpgsql;[cite: 2]

--5
CREATE OR REPLACE FUNCTION get_same_city_users(p_identifier VARCHAR)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR, email VARCHAR) AS $$
BEGIN
    RETURN QUERY
    SELECT other.first_name, other.last_name, other.email
    FROM users target_user
    JOIN users other ON target_user.city_id = other.city_id
    WHERE (target_user.email = p_identifier OR target_user.phone = p_identifier)
      AND other.id != target_user.id;
END;
$$ LANGUAGE plpgsql;[cite: 2]

--6
CREATE OR REPLACE FUNCTION get_top_buyers_since(p_date TIMESTAMP, p_limit INT)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR, total_tickets BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT u.first_name, u.last_name, COUNT(t.id) AS t_count
    FROM users u
    JOIN reservations r ON u.id = r.user_id
    JOIN reservation_items ri ON r.id = ri.reservation_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    WHERE t.issued_at >= p_date
    GROUP BY u.id, u.first_name, u.last_name
    ORDER BY t_count DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;[cite: 2]

--7
CREATE OR REPLACE FUNCTION get_canceled_tickets_by_sport(p_sport_name VARCHAR)
RETURNS TABLE (ticket_code VARCHAR, requested_at TIMESTAMP) AS $$
BEGIN
    RETURN QUERY
    SELECT t.ticket_code, c.requested_at
    FROM sports s
    JOIN matches m ON s.id = m.sport_id
    JOIN match_seats ms ON m.id = ms.match_id
    JOIN reservation_items ri ON ms.id = ri.match_seat_id
    JOIN tickets t ON ri.id = t.reservation_item_id
    JOIN reservations r ON ri.reservation_id = r.id
    JOIN cancellations c ON r.id = c.reservation_id
    WHERE s.name = p_sport_name
    ORDER BY c.requested_at ASC;
END;
$$ LANGUAGE plpgsql;[cite: 2]

--8
CREATE OR REPLACE FUNCTION get_top_reporters_by_subject(p_subject VARCHAR)
RETURNS TABLE (first_name VARCHAR, last_name VARCHAR, report_count BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT u.first_name, u.last_name, COUNT(ir.id) AS r_count
    FROM users u
    JOIN issue_reports ir ON u.id = ir.user_id
    WHERE ir.subject = p_subject
    GROUP BY u.id, u.first_name, u.last_name
    ORDER BY r_count DESC;
END;
$$ LANGUAGE plpgsql;[cite: 2]



-- Index on email and phone to speed up user searches (used in functions 1, 2, and 5)
CREATE INDEX idx_users_email_phone ON users(email, phone);[cite: 2]

-- Index on city name to speed up filtering by city (used in function 3)
CREATE INDEX idx_cities_name ON cities(name);[cite: 2]

-- Index on ticket issuance date to speed up date range queries (used in function 6)
CREATE INDEX idx_tickets_issued_at ON tickets(issued_at);[cite: 2]

-- Index on support issue reports subject (used in function 8)
CREATE INDEX idx_issue_reports_subject ON issue_reports(subject);[cite: 2]